repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: PowerShell

  # Updates the default branch for this repository.
  default_branch: master
